# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabtestquestion',
            name='B',
            field=models.CharField(default='第二种意思', max_length=128),
        ),
        migrations.AddField(
            model_name='vocabtestquestion',
            name='C',
            field=models.CharField(default='第三种意思', max_length=128),
        ),
        migrations.AddField(
            model_name='vocabtestquestion',
            name='D',
            field=models.CharField(default='第四种意思', max_length=128),
        ),
    ]
