# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_tester', '0002_auto_20171122_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabtestquestion',
            name='difficulty',
            field=models.IntegerField(default=-1),
        ),
    ]
