# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_tester', '0003_vocabtestquestion_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='微信名')),
                ('total_cnt', models.IntegerField(verbose_name='总答题数')),
                ('correct_cnt', models.IntegerField(verbose_name='正确数')),
            ],
            options={
                'verbose_name': '词汇量测试记录',
                'verbose_name_plural': '词汇量测试记录',
            },
        ),
        migrations.AlterModelOptions(
            name='vocabtestquestion',
            options={'verbose_name': '词汇量测试题', 'verbose_name_plural': '词汇量测试题'},
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='A',
            field=models.CharField(default='第一种意思', max_length=128, verbose_name='第一个选项'),
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='B',
            field=models.CharField(default='第二种意思', max_length=128, verbose_name='第二个选项'),
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='C',
            field=models.CharField(default='第三种意思', max_length=128, verbose_name='第三个选项'),
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='D',
            field=models.CharField(default='第四种意思', max_length=128, verbose_name='第四个选项'),
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='correct',
            field=models.CharField(default='A', max_length=16, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='difficulty',
            field=models.IntegerField(default=-1, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='vocabtestquestion',
            name='question',
            field=models.CharField(default='new word', max_length=128, verbose_name='问题'),
        ),
    ]
