# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_tester', '0004_auto_20171125_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabtestquestion',
            name='E',
            field=models.CharField(default='无正确答案', max_length=128, verbose_name='第五个选项'),
        ),
    ]
