# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_tester', '0005_vocabtestquestion_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='new word', max_length=128, verbose_name='词')),
                ('pos', models.CharField(default='new word', max_length=128, verbose_name='词')),
                ('exp', models.CharField(default='new word', max_length=128, verbose_name='词')),
                ('difficulty', models.IntegerField(default=0, verbose_name='难度等级')),
            ],
        ),
    ]
